package cat.dam.roig.cleanstream.ui;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

/**
 * Modal dialog that displays basic information about the application.
 *
 * <p>
 * This dialog is intended to provide a simple "About" screen:
 * <ul>
 * <li>Application name and version</li>
 * <li>Author / course information</li>
 * <li>Resources/tools used during development</li>
 * </ul>
 *
 * <p>
 * UI/UX notes:
 * <ul>
 * <li>Uses {@link AppTheme} to keep styling consistent with the rest of the
 * app.</li>
 * <li>Centers itself relative to the parent window.</li>
 * <li>Disposes itself on close (does not terminate the application).</li>
 * </ul>
 *
 * <p>
 * NetBeans Designer note: The {@code initComponents()} method is generated by
 * NetBeans and should not be edited manually. All custom UI code is
 * intentionally placed in {@link #initUI(Frame)}.
 *
 * @author metku
 */
public class AboutDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(AboutDialog.class.getName());

    /**
     * Creates a new AboutDialog.
     *
     * <p>
     * The dialog is initialized in two steps:
     * <ol>
     * <li>{@link #initComponents()} (NetBeans-generated)</li>
     * <li>{@link #initUI(Frame)} (custom layout and theming)</li>
     * </ol>
     *
     * @param parent parent frame used for centering the dialog (may be null)
     * @param modal true to block interaction with the parent while open
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Basic window placement / behavior
        setLocationRelativeTo(parent);
        setAlwaysOnTop(true);

        // Custom themed UI
        initUI(parent);
    }

    /**
     * Builds the custom UI elements (layout + theme + content).
     *
     * <p>
     * This method defines a "card" style dialog:
     * <ul>
     * <li>Background color + centered content</li>
     * <li>Card panel with padding and grouped sections</li>
     * <li>Close button aligned to the bottom-right</li>
     * </ul>
     *
     * @param parent parent frame used for centering the dialog
     */
    private void initUI(Frame parent) {

        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // Dialog background
        getContentPane().setBackground(AppTheme.BACKGROUND);
        setLayout(new BorderLayout());

        // Root centered panel (allows centered card layout)
        JPanel root = new JPanel(new GridBagLayout());
        root.setOpaque(false);

        // Card container with padding
        JPanel card = new JPanel(new GridBagLayout());
        card.setBackground(AppTheme.CARD);
        card.setBorder(new EmptyBorder(20, 24, 20, 24));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;

        // ===== HEADER =====
        JLabel lblTitle = new JLabel("CleanStream");
        lblTitle.setForeground(AppTheme.TEXT);
        lblTitle.setFont(lblTitle.getFont().deriveFont(Font.BOLD, 18f));

        JLabel lblVersion = new JLabel("Version 1.0");
        lblVersion.setForeground(AppTheme.MUTED);

        gbc.gridy = 0;
        gbc.insets = new Insets(0, 0, 4, 0);
        card.add(lblTitle, gbc);

        gbc.gridy = 1;
        gbc.insets = new Insets(0, 0, 14, 0);
        card.add(lblVersion, gbc);

        // ===== AUTHOR =====
        JLabel lblAuthor = new JLabel("Elias Roig Alcon");
        lblAuthor.setForeground(AppTheme.TEXT);

        JLabel lblCourse = new JLabel("FP 2 DAM - Desarrollo Interfaces");
        lblCourse.setForeground(AppTheme.MUTED);

        gbc.gridy = 2;
        gbc.insets = new Insets(0, 0, 4, 0);
        card.add(lblAuthor, gbc);

        gbc.gridy = 3;
        gbc.insets = new Insets(0, 0, 14, 0);
        card.add(lblCourse, gbc);

        // ===== RESOURCES =====
        JLabel lblResources = new JLabel("Resources used:");
        lblResources.setForeground(AppTheme.TEXT);
        lblResources.setFont(lblResources.getFont().deriveFont(Font.BOLD));

        gbc.gridy = 4;
        gbc.insets = new Insets(0, 0, 8, 0);
        card.add(lblResources, gbc);

        JPanel listPanel = new JPanel();
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));
        listPanel.setOpaque(false);

        listPanel.add(createMutedLabel("• ChatGPT"));
        listPanel.add(createMutedLabel("• Videos del profesor"));
        listPanel.add(createMutedLabel("• yt-dlp"));

        gbc.gridy = 5;
        gbc.insets = new Insets(0, 0, 16, 0);
        card.add(listPanel, gbc);

        // ===== CLOSE BUTTON =====
        JButton btnClose = new JButton("Close");
        btnClose.setFocusPainted(false);
        btnClose.setBackground(AppTheme.PRIMARY);
        btnClose.setForeground(Color.WHITE);
        btnClose.setBorder(new EmptyBorder(8, 18, 8, 18));
        btnClose.setPreferredSize(new Dimension(100, 36));

        // Close action: dispose dialog (safe for Swing, does not exit app)
        btnClose.addActionListener(e -> dispose());

        gbc.gridy = 6;
        gbc.insets = new Insets(0, 0, 0, 0);
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.NONE;
        gbc.weightx = 0;
        card.add(btnClose, gbc);

        root.add(card);
        add(root, BorderLayout.CENTER);

        setSize(420, 360);
        setLocationRelativeTo(parent);
    }

    /**
     * Creates a muted label used for secondary information lines.
     *
     * @param text label content
     * @return configured JLabel with muted color and vertical padding
     */
    private JLabel createMutedLabel(String text) {
        JLabel lbl = new JLabel(text);
        lbl.setForeground(AppTheme.MUTED);
        lbl.setBorder(new EmptyBorder(2, 0, 2, 0));
        return lbl;
    }

    /**
     * NetBeans Designer generated method.
     *
     * <p>
     * Warning: Do NOT modify this code manually. It is regenerated by the Form
     * Editor and any changes will be lost.
     * </p>
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About - CleanStream");
        setMinimumSize(new java.awt.Dimension(420, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
