package cat.dam.roig.cleanstream;

/**
 *
 * @author metku
 */
public class AboutDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AboutDialog.class.getName());

    /**
     * Creates new form AboutDialog
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblCursoInfo = new javax.swing.JLabel();
        lblRecursos = new javax.swing.JLabel();
        lblRecursoGtp = new javax.swing.JLabel();
        lblRecursoProfesor = new javax.swing.JLabel();
        lblRecursoYtdlp = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About - CleanStream");
        setMinimumSize(new java.awt.Dimension(420, 300));
        setPreferredSize(new java.awt.Dimension(420, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        lblName.setText("Elias Roig Alcon");
        getContentPane().add(lblName);
        lblName.setBounds(152, 69, 92, 18);

        lblCursoInfo.setText("FP 2 DAM Desarrollo Interfaces");
        getContentPane().add(lblCursoInfo);
        lblCursoInfo.setBounds(109, 115, 183, 18);

        lblRecursos.setText("Recursos utilizados:");
        getContentPane().add(lblRecursos);
        lblRecursos.setBounds(50, 151, 117, 18);

        lblRecursoGtp.setText("Chat GPT");
        getContentPane().add(lblRecursoGtp);
        lblRecursoGtp.setBounds(60, 180, 70, 18);

        lblRecursoProfesor.setText("Videos del profesor");
        getContentPane().add(lblRecursoProfesor);
        lblRecursoProfesor.setBounds(60, 210, 140, 18);

        lblRecursoYtdlp.setText("Yt-DLP");
        getContentPane().add(lblRecursoYtdlp);
        lblRecursoYtdlp.setBounds(60, 240, 42, 18);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(270, 240, 72, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblCursoInfo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRecursoGtp;
    private javax.swing.JLabel lblRecursoProfesor;
    private javax.swing.JLabel lblRecursoYtdlp;
    private javax.swing.JLabel lblRecursos;
    // End of variables declaration//GEN-END:variables
}
