package cat.dam.roig.cleanstream;

import cat.dam.roig.cleanstream.models.ResourceDownloaded;
import cat.dam.roig.cleanstream.services.DownloadsScanner;
import cat.dam.roig.cleanstream.utils.CommandExecutor;
import cat.dam.roig.cleanstream.utils.DetectOS;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingWorker;

/**
 *
 * @author metku
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private PreferencesPanel pnlPreferencesPanel;
    private DetectOS scanOS;
    private static final String YT_DLP_PATH = "/bin/yt-dlp";
    private static final String FFMPEG_PATH = "/bin/ffmpeg";      // opcional
    private static final String COOKIES_TXT = System.getProperty("user.home") + "/Downloads/youtube_cookies.txt"; // fallback
    private String lastDownloadedFile = null;
    private final DefaultListModel<ResourceDownloaded> downloadsModel = new DefaultListModel<>();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        pnlPreferencesPanel = new PreferencesPanel(this);

        setResizable(false);
        setLocationRelativeTo(null);

        // Same size and position
        pnlMainPanel.setBounds(0, 0, getWidth(), getHeight());
        pnlPreferencesPanel.setBounds(0, 0, getWidth(), getHeight());

        getContentPane().add(pnlPreferencesPanel);
        pnlPreferencesPanel.setVisible(false);
        pnlContent.setVisible(true);
    }

    // Navigation Methods
    public void showPreferences() {
        pnlContent.setVisible(false);
        pnlPreferencesPanel.setVisible(true);
        // Ordering the layers
        getContentPane().setComponentZOrder(pnlPreferencesPanel, 0);
    }

    public void showMain() {
        pnlPreferencesPanel.setVisible(false);
        pnlContent.setVisible(true);
        getContentPane().setComponentZOrder(pnlContent, 0);
    }

    public JTextArea getTxaLogArea() {
        return txaLogArea;
    }

    // ------- HELPERS --------
    private static void setExtractorClient(java.util.List<String> cmd, String client) {
        int idx = cmd.indexOf("--extractor-args");
        if (idx >= 0 && idx + 1 < cmd.size()) {
            cmd.set(idx + 1, "youtube:player_client=" + client);
        } else {
            cmd.add("--extractor-args");
            cmd.add("youtube:player_client=" + client);
        }
    }

    /**
     * Elimina una opción y su valor inmediatamente siguiente. Solo la primera
     * ocurrencia.
     */
    private static void removeOptionWithValue(java.util.List<String> cmd, String option) {
        for (int i = 0; i < cmd.size(); i++) {
            if (option.equals(cmd.get(i))) {
                cmd.remove(i);                  // quita la opción
                if (i < cmd.size()) {
                    cmd.remove(i); // quita el valor que ahora ocupa ese índice
                }
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFormat = new javax.swing.ButtonGroup();
        pnlContent = new javax.swing.JPanel();
        pnlMainPanel = new javax.swing.JPanel();
        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btnPaste = new java.awt.Button();
        btnClear = new java.awt.Button();
        lblFormat = new javax.swing.JLabel();
        rbVideo = new javax.swing.JRadioButton();
        rbAudio = new javax.swing.JRadioButton();
        lblOptions = new javax.swing.JLabel();
        chkM3U = new javax.swing.JCheckBox();
        chkOpenWhenDone = new javax.swing.JCheckBox();
        chkLimit = new javax.swing.JCheckBox();
        chkKbps = new javax.swing.JCheckBox();
        txtKbps = new javax.swing.JTextField();
        lblKbps = new javax.swing.JLabel();
        lblControls = new javax.swing.JLabel();
        btnDownload = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnOpenLast = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();
        scrLogArea = new javax.swing.JScrollPane();
        txaLogArea = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();
        lblActualDir = new javax.swing.JLabel();
        scpScanListPane = new javax.swing.JScrollPane();
        lstDownloadScanList = new javax.swing.JList<>();
        btnScanDownloadFolder = new javax.swing.JButton();
        mnbBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mniPreferences = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlContent.setLayout(new java.awt.CardLayout());

        pnlMainPanel.setLayout(null);

        lblUrl.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        lblUrl.setText("URL:");
        pnlMainPanel.add(lblUrl);
        lblUrl.setBounds(45, 10, 46, 29);

        txtUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUrlActionPerformed(evt);
            }
        });
        pnlMainPanel.add(txtUrl);
        txtUrl.setBounds(109, 13, 350, 24);

        btnPaste.setLabel("Paste");
        pnlMainPanel.add(btnPaste);
        btnPaste.setBounds(477, 14, 47, 25);

        btnClear.setLabel("Clear");
        pnlMainPanel.add(btnClear);
        btnClear.setBounds(534, 14, 46, 25);

        lblFormat.setText("Format:");
        pnlMainPanel.add(lblFormat);
        lblFormat.setBounds(45, 70, 47, 18);

        bgFormat.add(rbVideo);
        rbVideo.setText("Video");
        rbVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVideoActionPerformed(evt);
            }
        });
        pnlMainPanel.add(rbVideo);
        rbVideo.setBounds(97, 68, 57, 22);

        bgFormat.add(rbAudio);
        rbAudio.setText("Audio");
        pnlMainPanel.add(rbAudio);
        rbAudio.setBounds(181, 68, 58, 22);

        lblOptions.setText("Options:");
        pnlMainPanel.add(lblOptions);
        lblOptions.setBounds(40, 110, 51, 18);

        chkM3U.setText("Create .m3u");
        pnlMainPanel.add(chkM3U);
        chkM3U.setBounds(60, 140, 95, 22);

        chkOpenWhenDone.setText("Open when done");
        pnlMainPanel.add(chkOpenWhenDone);
        chkOpenWhenDone.setBounds(170, 140, 126, 22);

        chkLimit.setText("Limit Speed");
        pnlMainPanel.add(chkLimit);
        chkLimit.setBounds(310, 140, 93, 22);
        pnlMainPanel.add(chkKbps);
        chkKbps.setBounds(420, 140, 19, 19);
        pnlMainPanel.add(txtKbps);
        txtKbps.setBounds(450, 140, 34, 24);

        lblKbps.setText("Kbsp");
        pnlMainPanel.add(lblKbps);
        lblKbps.setBounds(490, 140, 30, 18);

        lblControls.setText("Controles:");
        pnlMainPanel.add(lblControls);
        lblControls.setBounds(40, 190, 61, 18);

        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        pnlMainPanel.add(btnDownload);
        btnDownload.setBounds(20, 230, 158, 24);

        btnStop.setText("Stop");
        pnlMainPanel.add(btnStop);
        btnStop.setBounds(210, 230, 169, 24);

        btnOpenLast.setText("Open last");
        pnlMainPanel.add(btnOpenLast);
        btnOpenLast.setBounds(400, 230, 158, 24);

        lblOutput.setText("Output:");
        pnlMainPanel.add(lblOutput);
        lblOutput.setBounds(40, 290, 47, 18);

        txaLogArea.setColumns(20);
        txaLogArea.setRows(5);
        scrLogArea.setViewportView(txaLogArea);

        pnlMainPanel.add(scrLogArea);
        scrLogArea.setBounds(30, 320, 536, 96);
        pnlMainPanel.add(lblStatus);
        lblStatus.setBounds(30, 450, 115, 27);
        pnlMainPanel.add(lblActualDir);
        lblActualDir.setBounds(400, 460, 163, 27);

        pnlContent.add(pnlMainPanel, "card3");

        getContentPane().add(pnlContent);
        pnlContent.setBounds(0, 0, 590, 630);

        scpScanListPane.setViewportView(lstDownloadScanList);

        getContentPane().add(scpScanListPane);
        scpScanListPane.setBounds(600, 70, 560, 350);

        btnScanDownloadFolder.setText("Scan");
        btnScanDownloadFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanDownloadFolderActionPerformed(evt);
            }
        });
        getContentPane().add(btnScanDownloadFolder);
        btnScanDownloadFolder.setBounds(1060, 30, 72, 24);

        mnuFile.setText("File");

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        mnbBar.add(mnuFile);

        mnuEdit.setText("Edit");

        mniPreferences.setText("Preferences");
        mniPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPreferencesActionPerformed(evt);
            }
        });
        mnuEdit.add(mniPreferences);

        mnbBar.add(mnuEdit);

        mnuHelp.setText("Help");

        mniAbout.setText("About");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mniAbout);

        mnbBar.add(mnuHelp);

        setJMenuBar(mnbBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrlActionPerformed

    private void rbVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVideoActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPreferencesActionPerformed
        // TODO add your handling code here:
        showPreferences();
    }//GEN-LAST:event_mniPreferencesActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:
        String ytDlpPath = pnlPreferencesPanel.getTxtYtDlpPath();
//        String ytDlpPath = YT_DLP_PATH; // Ruta fija como acordamos
        final String downloadDir = scanOS.resolveDownloadDir(pnlPreferencesPanel.getTxtDownloadsDir().trim());
        String url = txtUrl.getText().trim();

        if (url.isBlank()) {
            JOptionPane.showMessageDialog(this, "Video URL is missing.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Construcción del comando
        java.util.List<String> command = new java.util.ArrayList<>();
        command.add(ytDlpPath);
        command.add("-f");
        command.add("bv*+ba/b/22/18"); // incluye fallback progresivo
        if (!downloadDir.isBlank()) {
            command.add("-P");
            command.add(downloadDir);
            command.add("-o");
            command.add("%(title)s.%(ext)s");
        }
        // Ruta fija a ffmpeg
        command.add("--ffmpeg-location");
        command.add(FFMPEG_PATH);

        // Flags de estabilidad
        command.add("--force-ipv4");
        command.add("--http-chunk-size");
        command.add("10M");
        command.add("--user-agent");
        command.add("Mozilla/5.0");
        command.add("--add-header");
        command.add("Referer:https://www.youtube.com/");
        command.add("--add-header");
        command.add("Accept-Language:es-ES,es;q=0.9");
        command.add("--concurrent-fragments");
        command.add("1");
        command.add("--retries");
        command.add("infinite");
        command.add("--fragment-retries");
        command.add("infinite");
        command.add("--cookies-from-browser");
        command.add("vivaldi:Default::" + System.getProperty("user.home") + "/.config/vivaldi");

        // URL al final
        command.add(url);

        // Mostrar comando y versión
        java.util.List<String> verCmd = java.util.List.of(ytDlpPath, "--version");
        JTextArea log = getTxaLogArea();
        log.setText("");
        log.append("CMD: " + String.join(" ", command) + "\n\n");
        btnDownload.setEnabled(false);

        // SwingWorker
        SwingWorker<Integer, String> worker = new SwingWorker<>() {
            @Override
            protected Integer doInBackground() {
                try {
                    // 0) versión
                    CommandExecutor.runStreaming(java.util.List.of(YT_DLP_PATH, "--version"),
                            line -> publish("[yt-dlp --version] " + line));

                    // === 1) INTENTO WEB (con cookies) ===
                    java.util.List<String> cmdWeb = new java.util.ArrayList<>(command);
                    setExtractorClient(cmdWeb, "web");
                    publish("[try] web + cookies");
                    int exitWeb = CommandExecutor.runStreaming(cmdWeb, this::publish);
                    if (exitWeb == 0) {
                        return 0; // ✅ no reintentes si ya fue bien
                    }
                    // === 2) FALLBACK ANDROID (sin cookies) ===
                    java.util.List<String> cmdAndroid = new java.util.ArrayList<>(command);
                    setExtractorClient(cmdAndroid, "android");
                    // Android no soporta cookies → quitar opción y su valor
                    removeOptionWithValue(cmdAndroid, "--cookies-from-browser");
                    publish("[retry] android (sin cookies)");
                    int exitAndroid = CommandExecutor.runStreaming(cmdAndroid, this::publish);
                    return exitAndroid;

                    // (Opcional) podrías probar iOS aquí, pero requiere PO token; mejor omitir.
                } catch (Exception e) {
                    publish("ERROR: " + e.getMessage());
                    return -1;
                }
            }

            @Override
            protected void process(java.util.List<String> lines) {
                for (String line : lines) {
                    log.append(line + "\n");

                    // Detectar el archivo descargado
                    if (line.contains("Destination:")) {
                        String path = line.substring(line.indexOf("Destination:") + "Destination:".length()).trim();
                        lastDownloadedFile = path;
                    }
                }
            }

            @Override
            protected void done() {
                try {
                    int exit = get();
                    log.append("\nProceso finalizado con código: " + exit + "\n");
                    log.append("OS Detected: " + DetectOS.detectOS());
                    log.append("\nDownload dir (final): " + downloadDir);

                    // Solo abrir si el checkbox está marcado y el proceso fue correcto
                    if (exit == 0 && chkOpenWhenDone.isSelected() && lastDownloadedFile != null) {
                        java.io.File file = new java.io.File(lastDownloadedFile);
                        if (file.exists()) {
                            log.append("Playing: " + file.getName() + "\n");
                            java.awt.Desktop.getDesktop().open(file);
                        } else {
                            log.append("Couldn't find the downloaded file.\n");
                        }
                    }

                } catch (Exception ex) {
                    log.append("ERROR when finished: " + ex.getMessage() + "\n");
                } finally {
                    btnDownload.setEnabled(true);
                }
            }
        };

        worker.execute();
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutActionPerformed
        // TODO add your handling code here:
        AboutDialog dlg = new AboutDialog(this, true); // modal
        dlg.setVisible(true);
    }//GEN-LAST:event_mniAboutActionPerformed

    private void btnScanDownloadFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanDownloadFolderActionPerformed
        // 1) Leer texto del panel de preferencias
        String input = pnlPreferencesPanel.getTxtScanDownloadsFolder().getText();

        // 2) Resolver SIEMPRE una ruta válida (con fallback a Descargas/yt)
        String finalDirStr = DetectOS.resolveDownloadDir(input);
        Path downloads = Paths.get(finalDirStr);

        // 3) Ejecutar el escaneo en background (no bloquear EDT)
        btnScanDownloadFolder.setEnabled(false);
        SwingWorker<List<ResourceDownloaded>, Void> worker
                = new SwingWorker<>() {
            @Override
            protected List<ResourceDownloaded> doInBackground() {
                try {
                    DownloadsScanner scanner = new DownloadsScanner();
                    // false = no recursivo. Cambia a true si quieres subcarpetas.
                    return scanner.scan(downloads, false);
                } catch (java.io.IOException e) {
                    // Log opcional
                    System.err.println("Scan error: " + e.getMessage());
                    return java.util.Collections.emptyList();
                }
            }

            @Override
            protected void done() {
                try {
                    List<ResourceDownloaded> lista = get();

                    if (lista == null) {
                        System.err.println("Scan devolvió null");
                        downloadsModel.clear();
                        return;
                    }

                    // (Opcional) log a consola
                    System.out.println("Scan OK. Items: " + lista.size());
                    // (Opcional) log a consola
                    lista.forEach(r -> System.out.printf(
                            "%s | %s | %d bytes | %s | %s | %s%n",
                            r.getName(), r.getRoute(), r.getSize(), r.getMimeType(),
                            r.getExtension(), r.getDownloadDate()
                    ));

                    downloadsModel.clear();
                    
                    for (ResourceDownloaded r : lista) {
                        downloadsModel.addElement(r);
                    }

                    lstDownloadScanList.setModel(downloadsModel);
                    // TODO: aquí actualiza tu JTable/Model con 'lista'
                    // e.g. tableModel.setData(lista);
                } catch (Exception ex) {
                    System.err.println("Finished with error: " + ex.getMessage());
                } finally {
                    btnScanDownloadFolder.setEnabled(true);
                }
            }
        };

        worker.execute();
    }//GEN-LAST:event_btnScanDownloadFolderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFormat;
    private java.awt.Button btnClear;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnOpenLast;
    private java.awt.Button btnPaste;
    private javax.swing.JButton btnScanDownloadFolder;
    private javax.swing.JButton btnStop;
    private javax.swing.JCheckBox chkKbps;
    private javax.swing.JCheckBox chkLimit;
    private javax.swing.JCheckBox chkM3U;
    private javax.swing.JCheckBox chkOpenWhenDone;
    private javax.swing.JLabel lblActualDir;
    private javax.swing.JLabel lblControls;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblKbps;
    private javax.swing.JLabel lblOptions;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JList<ResourceDownloaded> lstDownloadScanList;
    private javax.swing.JMenuBar mnbBar;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniPreferences;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlMainPanel;
    private javax.swing.JRadioButton rbAudio;
    private javax.swing.JRadioButton rbVideo;
    private javax.swing.JScrollPane scpScanListPane;
    private javax.swing.JScrollPane scrLogArea;
    private javax.swing.JTextArea txaLogArea;
    private javax.swing.JTextField txtKbps;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
