package cat.dam.roig.cleanstream;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author metku
 */
public class PreferencesPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;

    /**
     * Creates new form MainPanel
     *
     * @param mainFrame
     */
    public PreferencesPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    
    // ------- GETTERS --------
    
    public String getTxtYtDlpPath() {
        return txtYtDlpPath.getText().trim();
    }

    public String getTxtFfpmegDir() {
        return txtFfpmegDir.getText().trim();
    }

    public String getTxtFfprobeDir() {
        return txtFfprobeDir.getText().trim();
    }

    public String getTxtTempDir() {
        return txtTempDir.getText().trim();
    }

    public String getTxtDownloadsDir() {
        return txtDownloadsDir.getText().trim();
    }

    public JTextField getTxtScanDownloadsFolder() {
        return txtScanDownloadsFolder;
    }
    
    // Helpers Reusable
    /**
     * Diálogo para elegir ARCHIVO ejecutable (yt-dlp, ffmpeg, ffprobe)
     */
    private void browseFileInto(JTextField target, String title, boolean tryExeFilter) {
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle(title);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        // Si hay valor previo, ábrelo ahí
        File current = pathToExistingFileOrDir(target.getText());
        if (current != null) {
            fc.setCurrentDirectory(current.isDirectory() ? current : current.getParentFile());
            if (current.isFile()) {
                fc.setSelectedFile(current);
            }
        }
        
        // En Windows puedes filtrar .exe; en Linux/Mac no tiene sentido
        if (tryExeFilter && isWindows()) {
            fc.setAcceptAllFileFilterUsed(true);
            fc.setFileFilter(new FileNameExtensionFilter("Executables (*.exe)", "exe"));
        }

        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            target.setText(f.getAbsolutePath());
            // (opcional) validación rápida
            if (!f.canExecute()) {
                JOptionPane.showMessageDialog(this,
                        "Warning: the selected file can not be executed.\n" + f,
                        "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    /**
     * Diálogo para elegir CARPETA (descargas, temporales)
     */
    private void browseDirectoryInto(JTextField target, String title) {
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle(title);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setAcceptAllFileFilterUsed(false);

        File current = pathToExistingFileOrDir(target.getText());
        if (current != null) {
            fc.setCurrentDirectory(current.isDirectory() ? current : current.getParentFile());
            if (current.isDirectory()) {
                fc.setSelectedFile(current);
            }
        }

        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File dir = fc.getSelectedFile();
            target.setText(dir.getAbsolutePath());
        }
    }

    private static boolean isWindows() {
        String os = System.getProperty("os.name", "").toLowerCase();
        return os.contains("win");
    }

    private static File pathToExistingFileOrDir(String path) {
        if (path == null || path.isBlank()) {
            return null;
        }
        File f = new File(path.trim());
        return f.exists() ? f : null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgQuality = new javax.swing.ButtonGroup();
        lblBinaries = new javax.swing.JLabel();
        lblYtDlp = new javax.swing.JLabel();
        txtYtDlpPath = new javax.swing.JTextField();
        btnYtDplBrowse = new javax.swing.JButton();
        lblFfpmeg = new javax.swing.JLabel();
        txtFfpmegDir = new javax.swing.JTextField();
        btnFfpmegBrowse = new javax.swing.JButton();
        lblFfprobe = new javax.swing.JLabel();
        txtFfprobeDir = new javax.swing.JTextField();
        btnFfprobeBrowse = new javax.swing.JButton();
        lblRoutes = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        txtTempDir = new javax.swing.JTextField();
        btnTempBrowse = new javax.swing.JButton();
        lblDownloads = new javax.swing.JLabel();
        txtDownloadsDir = new javax.swing.JTextField();
        btnDownloadsBrowse = new javax.swing.JButton();
        lblBehaviour = new javax.swing.JLabel();
        chkDeleteIntermediates = new javax.swing.JCheckBox();
        chkKeepName = new javax.swing.JCheckBox();
        chkAutoplay = new javax.swing.JCheckBox();
        chkOverwrite = new javax.swing.JCheckBox();
        lblQuality = new javax.swing.JLabel();
        rbBest = new javax.swing.JRadioButton();
        rb1080 = new javax.swing.JRadioButton();
        rb720 = new javax.swing.JRadioButton();
        rbAudioOnly = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblScanDownloads = new javax.swing.JLabel();
        txtScanDownloadsFolder = new javax.swing.JTextField();
        btnScanDownloadsFolder = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(590, 518));
        setLayout(null);

        lblBinaries.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblBinaries.setText("Binaries:");
        add(lblBinaries);
        lblBinaries.setBounds(30, 30, 70, 23);

        lblYtDlp.setText("yt-dlp:");
        add(lblYtDlp);
        lblYtDlp.setBounds(40, 60, 70, 18);

        txtYtDlpPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYtDlpPathActionPerformed(evt);
            }
        });
        add(txtYtDlpPath);
        txtYtDlpPath.setBounds(110, 60, 310, 24);

        btnYtDplBrowse.setText("Browse...");
        btnYtDplBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYtDplBrowseActionPerformed(evt);
            }
        });
        add(btnYtDplBrowse);
        btnYtDplBrowse.setBounds(430, 60, 90, 24);

        lblFfpmeg.setText("ffpmeg:");
        add(lblFfpmeg);
        lblFfpmeg.setBounds(40, 100, 70, 18);
        add(txtFfpmegDir);
        txtFfpmegDir.setBounds(110, 100, 310, 24);

        btnFfpmegBrowse.setText("Browse...");
        btnFfpmegBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFfpmegBrowseActionPerformed(evt);
            }
        });
        add(btnFfpmegBrowse);
        btnFfpmegBrowse.setBounds(430, 100, 90, 24);

        lblFfprobe.setText("ffprobe:");
        add(lblFfprobe);
        lblFfprobe.setBounds(40, 140, 70, 18);
        add(txtFfprobeDir);
        txtFfprobeDir.setBounds(110, 140, 310, 24);

        btnFfprobeBrowse.setText("Browse...");
        btnFfprobeBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFfprobeBrowseActionPerformed(evt);
            }
        });
        add(btnFfprobeBrowse);
        btnFfprobeBrowse.setBounds(430, 140, 90, 24);

        lblRoutes.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblRoutes.setText("Routes:");
        add(lblRoutes);
        lblRoutes.setBounds(30, 180, 70, 23);

        lblTemp.setText("Temp:");
        add(lblTemp);
        lblTemp.setBounds(40, 220, 70, 18);
        add(txtTempDir);
        txtTempDir.setBounds(110, 220, 310, 24);

        btnTempBrowse.setText("Browse...");
        btnTempBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempBrowseActionPerformed(evt);
            }
        });
        add(btnTempBrowse);
        btnTempBrowse.setBounds(430, 220, 90, 24);

        lblDownloads.setText("Downloads:");
        add(lblDownloads);
        lblDownloads.setBounds(40, 260, 70, 18);
        add(txtDownloadsDir);
        txtDownloadsDir.setBounds(120, 260, 300, 24);

        btnDownloadsBrowse.setText("Browse...");
        btnDownloadsBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadsBrowseActionPerformed(evt);
            }
        });
        add(btnDownloadsBrowse);
        btnDownloadsBrowse.setBounds(430, 260, 90, 24);

        lblBehaviour.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblBehaviour.setText("Behaving:");
        add(lblBehaviour);
        lblBehaviour.setBounds(590, 30, 110, 23);

        chkDeleteIntermediates.setText("Delete intermediates files");
        add(chkDeleteIntermediates);
        chkDeleteIntermediates.setBounds(680, 40, 190, 22);

        chkKeepName.setText("Keep original name");
        add(chkKeepName);
        chkKeepName.setBounds(680, 70, 150, 22);

        chkAutoplay.setText("Autoplay on finish");
        add(chkAutoplay);
        chkAutoplay.setBounds(890, 40, 170, 22);

        chkOverwrite.setText("Overwrite if exists");
        add(chkOverwrite);
        chkOverwrite.setBounds(890, 70, 170, 22);

        lblQuality.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblQuality.setText("Quality:");
        add(lblQuality);
        lblQuality.setBounds(590, 120, 110, 23);

        bgQuality.add(rbBest);
        rbBest.setText("Best Available");
        add(rbBest);
        rbBest.setBounds(670, 120, 105, 22);

        bgQuality.add(rb1080);
        rb1080.setText("1080p");
        add(rb1080);
        rb1080.setBounds(800, 120, 59, 22);

        bgQuality.add(rb720);
        rb720.setText("720p");
        add(rb720);
        rb720.setBounds(880, 120, 60, 22);

        bgQuality.add(rbAudioOnly);
        rbAudioOnly.setText("Only Audio");
        add(rbAudioOnly);
        rbAudioOnly.setBounds(950, 120, 89, 22);

        btnSave.setText("Save");
        add(btnSave);
        btnSave.setBounds(50, 460, 72, 24);

        btnCancel.setText("Back");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel);
        btnCancel.setBounds(450, 460, 72, 24);

        btnReset.setText("Reset");
        add(btnReset);
        btnReset.setBounds(130, 460, 72, 24);

        lblScanDownloads.setText("Scan Files:");
        add(lblScanDownloads);
        lblScanDownloads.setBounds(40, 300, 70, 18);
        add(txtScanDownloadsFolder);
        txtScanDownloadsFolder.setBounds(120, 300, 300, 24);

        btnScanDownloadsFolder.setText("Browse...");
        btnScanDownloadsFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanDownloadsFolderActionPerformed(evt);
            }
        });
        add(btnScanDownloadsFolder);
        btnScanDownloadsFolder.setBounds(430, 300, 90, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void btnYtDplBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYtDplBrowseActionPerformed
        // TODO add your handling code here:
        browseFileInto(txtYtDlpPath, "Select the exe of yt-dlp", true);
    }//GEN-LAST:event_btnYtDplBrowseActionPerformed

    private void btnFfpmegBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFfpmegBrowseActionPerformed
        // TODO add your handling code here:
        browseFileInto(txtFfpmegDir, "Select the exe of ffmpeg", true);
    }//GEN-LAST:event_btnFfpmegBrowseActionPerformed

    private void btnFfprobeBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFfprobeBrowseActionPerformed
        // TODO add your handling code here:
        browseFileInto(txtFfprobeDir, "Select the exe of ffprobe", true);
    }//GEN-LAST:event_btnFfprobeBrowseActionPerformed

    private void btnTempBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempBrowseActionPerformed
        // TODO add your handling code here:
        browseDirectoryInto(txtTempDir, "Select the folder of temp files");
    }//GEN-LAST:event_btnTempBrowseActionPerformed

    private void btnDownloadsBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadsBrowseActionPerformed
        // TODO add your handling code here:
        browseDirectoryInto(txtDownloadsDir, "Select the downloads folder");
    }//GEN-LAST:event_btnDownloadsBrowseActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        mainFrame.showMain();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtYtDlpPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYtDlpPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYtDlpPathActionPerformed

    private void btnScanDownloadsFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanDownloadsFolderActionPerformed
        // TODO add your handling code here:
        browseDirectoryInto(txtScanDownloadsFolder, "Select the downloads folder");
    }//GEN-LAST:event_btnScanDownloadsFolderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgQuality;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDownloadsBrowse;
    private javax.swing.JButton btnFfpmegBrowse;
    private javax.swing.JButton btnFfprobeBrowse;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnScanDownloadsFolder;
    private javax.swing.JButton btnTempBrowse;
    private javax.swing.JButton btnYtDplBrowse;
    private javax.swing.JCheckBox chkAutoplay;
    private javax.swing.JCheckBox chkDeleteIntermediates;
    private javax.swing.JCheckBox chkKeepName;
    private javax.swing.JCheckBox chkOverwrite;
    private javax.swing.JLabel lblBehaviour;
    private javax.swing.JLabel lblBinaries;
    private javax.swing.JLabel lblDownloads;
    private javax.swing.JLabel lblFfpmeg;
    private javax.swing.JLabel lblFfprobe;
    private javax.swing.JLabel lblQuality;
    private javax.swing.JLabel lblRoutes;
    private javax.swing.JLabel lblScanDownloads;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblYtDlp;
    private javax.swing.JRadioButton rb1080;
    private javax.swing.JRadioButton rb720;
    private javax.swing.JRadioButton rbAudioOnly;
    private javax.swing.JRadioButton rbBest;
    private javax.swing.JTextField txtDownloadsDir;
    private javax.swing.JTextField txtFfpmegDir;
    private javax.swing.JTextField txtFfprobeDir;
    private javax.swing.JTextField txtScanDownloadsFolder;
    private javax.swing.JTextField txtTempDir;
    private javax.swing.JTextField txtYtDlpPath;
    // End of variables declaration//GEN-END:variables
}
