package cat.dam.roig.cleanstream;

/**
 *
 * @author metku
 */
public class PreferencesPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public PreferencesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBinaries = new javax.swing.JLabel();
        lblYtDlp = new javax.swing.JLabel();
        txtYtDlpPath = new javax.swing.JTextField();
        btnYtDplBrowse = new javax.swing.JButton();
        lblFfpmeg = new javax.swing.JLabel();
        txtFfpmegDir = new javax.swing.JTextField();
        btnFfpmegBrowse = new javax.swing.JButton();
        lblFfprobe = new javax.swing.JLabel();
        txtFfprobeDir = new javax.swing.JTextField();
        btnFfprobeBrowse = new javax.swing.JButton();
        lblRoutes = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        txtTempDir = new javax.swing.JTextField();
        btnTempBrowse = new javax.swing.JButton();
        lblDownloads = new javax.swing.JLabel();
        txtDownloadsDir = new javax.swing.JTextField();
        btnDownloadsBrowse = new javax.swing.JButton();
        lblBehaviour = new javax.swing.JLabel();

        setLayout(null);

        lblBinaries.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblBinaries.setText("Binaries:");
        add(lblBinaries);
        lblBinaries.setBounds(30, 30, 70, 23);

        lblYtDlp.setText("yt-dlp:");
        add(lblYtDlp);
        lblYtDlp.setBounds(40, 60, 70, 18);
        add(txtYtDlpPath);
        txtYtDlpPath.setBounds(110, 60, 310, 24);

        btnYtDplBrowse.setText("Browse...");
        btnYtDplBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYtDplBrowseActionPerformed(evt);
            }
        });
        add(btnYtDplBrowse);
        btnYtDplBrowse.setBounds(430, 60, 90, 24);

        lblFfpmeg.setText("ffpmeg:");
        add(lblFfpmeg);
        lblFfpmeg.setBounds(40, 100, 70, 18);
        add(txtFfpmegDir);
        txtFfpmegDir.setBounds(110, 100, 310, 24);

        btnFfpmegBrowse.setText("Browse...");
        btnFfpmegBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFfpmegBrowseActionPerformed(evt);
            }
        });
        add(btnFfpmegBrowse);
        btnFfpmegBrowse.setBounds(430, 100, 90, 24);

        lblFfprobe.setText("ffprobe:");
        add(lblFfprobe);
        lblFfprobe.setBounds(40, 140, 70, 18);
        add(txtFfprobeDir);
        txtFfprobeDir.setBounds(110, 140, 310, 24);

        btnFfprobeBrowse.setText("Browse...");
        btnFfprobeBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFfprobeBrowseActionPerformed(evt);
            }
        });
        add(btnFfprobeBrowse);
        btnFfprobeBrowse.setBounds(430, 140, 90, 24);

        lblRoutes.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblRoutes.setText("Routes:");
        add(lblRoutes);
        lblRoutes.setBounds(30, 210, 70, 23);

        lblTemp.setText("Temp:");
        add(lblTemp);
        lblTemp.setBounds(40, 250, 70, 18);
        add(txtTempDir);
        txtTempDir.setBounds(110, 250, 310, 24);

        btnTempBrowse.setText("Browse...");
        btnTempBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempBrowseActionPerformed(evt);
            }
        });
        add(btnTempBrowse);
        btnTempBrowse.setBounds(430, 250, 90, 24);

        lblDownloads.setText("ffprobe:");
        add(lblDownloads);
        lblDownloads.setBounds(40, 290, 70, 18);
        add(txtDownloadsDir);
        txtDownloadsDir.setBounds(110, 290, 310, 24);

        btnDownloadsBrowse.setText("Browse...");
        btnDownloadsBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadsBrowseActionPerformed(evt);
            }
        });
        add(btnDownloadsBrowse);
        btnDownloadsBrowse.setBounds(430, 290, 90, 24);

        lblBehaviour.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        lblBehaviour.setText("Behaving:");
        add(lblBehaviour);
        lblBehaviour.setBounds(30, 360, 110, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnYtDplBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYtDplBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYtDplBrowseActionPerformed

    private void btnFfpmegBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFfpmegBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFfpmegBrowseActionPerformed

    private void btnFfprobeBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFfprobeBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFfprobeBrowseActionPerformed

    private void btnTempBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTempBrowseActionPerformed

    private void btnDownloadsBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadsBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDownloadsBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownloadsBrowse;
    private javax.swing.JButton btnFfpmegBrowse;
    private javax.swing.JButton btnFfprobeBrowse;
    private javax.swing.JButton btnTempBrowse;
    private javax.swing.JButton btnYtDplBrowse;
    private javax.swing.JLabel lblBehaviour;
    private javax.swing.JLabel lblBinaries;
    private javax.swing.JLabel lblDownloads;
    private javax.swing.JLabel lblFfpmeg;
    private javax.swing.JLabel lblFfprobe;
    private javax.swing.JLabel lblRoutes;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblYtDlp;
    private javax.swing.JTextField txtDownloadsDir;
    private javax.swing.JTextField txtFfpmegDir;
    private javax.swing.JTextField txtFfprobeDir;
    private javax.swing.JTextField txtTempDir;
    private javax.swing.JTextField txtYtDlpPath;
    // End of variables declaration//GEN-END:variables
}
