package cat.dam.roig.cleanstream;

/**
 *
 * @author metku
 */
public class PreferencesPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public PreferencesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBinaries = new javax.swing.JLabel();
        lblYtDlp = new javax.swing.JLabel();
        txtYtDlpPath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblYtDlp1 = new javax.swing.JLabel();
        txtYtDlpPath1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lblYtDlp2 = new javax.swing.JLabel();
        txtYtDlpPath2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setLayout(null);

        lblBinaries.setText("Binaries");
        add(lblBinaries);
        lblBinaries.setBounds(40, 10, 47, 18);

        lblYtDlp.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblYtDlp.setText("yt-dlp:");
        add(lblYtDlp);
        lblYtDlp.setBounds(40, 40, 70, 20);
        add(txtYtDlpPath);
        txtYtDlpPath.setBounds(110, 40, 310, 24);

        jButton1.setText("Browse...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(430, 40, 90, 24);

        lblYtDlp1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblYtDlp1.setText("ffmeg:");
        add(lblYtDlp1);
        lblYtDlp1.setBounds(40, 80, 70, 20);
        add(txtYtDlpPath1);
        txtYtDlpPath1.setBounds(110, 80, 310, 24);

        jButton2.setText("Browse...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(430, 80, 90, 24);

        lblYtDlp2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblYtDlp2.setText("ffprobe:");
        add(lblYtDlp2);
        lblYtDlp2.setBounds(40, 120, 70, 20);
        add(txtYtDlpPath2);
        txtYtDlpPath2.setBounds(110, 120, 310, 24);

        jButton3.setText("Browse...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(430, 120, 90, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lblBinaries;
    private javax.swing.JLabel lblYtDlp;
    private javax.swing.JLabel lblYtDlp1;
    private javax.swing.JLabel lblYtDlp2;
    private javax.swing.JTextField txtYtDlpPath;
    private javax.swing.JTextField txtYtDlpPath1;
    private javax.swing.JTextField txtYtDlpPath2;
    // End of variables declaration//GEN-END:variables
}
